### ISSUE TITLE
Src & Dst information as part of MovmentPath

### ISSUE THREAD

**Issue by donman2007** [nathanglevy/AutoEra#7]
i want to implment the Patrol SM as example
let's say, patrol between two points
A <-------------------> B

so in the Update Method i need to know when Characheter reached dest, i can do it in 2 ways:
1. check if the char not in transit (assuming reached dest) --> have not way to do it today
2. check char Location vs Path.Dst --> but MovmentPath has no such capability

please help adding these 2 capabilities to the 2 classes.
Thanks
Ahmad

**Comment by nathanglevy** [comment]
Added both 1 & 2:
**#1. Check if in transit**
Character now has a method:
IsACurrentPathInTransit()
Which will return true if has a current path set which it has not completed.

**#2. Check by getting info from the path**
Character also has a GetCurrentMovementPath() method which will return the current path it is doing.
Now, movement path instance gives access to "source" and "destination" properties.

All of the above in latest release I am doing now.
