### ISSUE TITLE
vector3 vs vector2

### ISSUE THREAD

**Issue by donman2007** [nathanglevy/AutoEra#8]
it's very annotying that part of the code require Vector3 and other require Vector2. please support That FindShortestPath and other PathCalculator methods get Vector3 by default and you can move it to vector2 inside.

By the way, IGameWorld is not complete, pathCalculator as examplle is missing, make sure you well define it.

Thanks
Ahmad

**Comment by nathanglevy** [comment]
Changed FindShortest path to have overloads for 2Vec and 3Vec
Movement path is now in 3Vec
You also have a utility extension on 2Vec called toVec3 to transform it to 3Vec
Also vis-versa for 3Vec.

Tell me if you see any other places where it is still wrong. Closing this for now.

**Comment by nathanglevy** [comment]
BTW you also have a new property called PathCalculator on the gameworld which will take care of all path calculations.
